language: go
go:
  - 1.9
  - "1.10"
  - tip
sudo: false
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - make ci
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT